#test1_change
---
# this file assumes Automation Hub is the default source
collections:

- name: community.libvirt
  # version: 1.2.0
  source: https://galaxy.ansible.com

- name: community.vmware
  # version: 1.5.2
  source: https://galaxy.ansible.com

- name: community.general