---
# tasks file for vmware_remove_snapshot
# - name: Find all the snapshots older then 3 days in Vmware
#   community.vmware.vmware_guest_snapshot_info:
#       hostname: "{{ vcenter_hostname }}"
#       username: "{{ vcenter_username }}"
#       password: "{{ _password_ }}"
#       datacenter: "{{ datacenter_name }}"
#       folder: /{{ datacenter_name }}/vm/
#       name: "{{ guest_name }}"
#   register: snapshot_info

# - name: Remove Snapshot older then 3 days in VSphere
#   community.vmware.vmware_guest_snapshot:
#       datacenter: "Plainview"
#       folder: "RHEL-Automation"
#       name: "{{ guest_name }}"
#       state: remove_all
#       snapshot_name: "{{item}}"
#       validate_certs: false
#   loop: "{{snapshot_info.stdout}}"
#   delegate_to: localhost
- name: Get VM facts
  community.vmware.vmware_guest_info:
    datacenter: "Plainview"
    name: "{{ vm_name }}"
    validate_certs: "no"
  register: vm_facts

- name: Get the latest snapshot of the vm
  community.vmware.vmware_guest_snapshot_info:
    datacenter: Plainview
    folder: RHEL-Automation
    name: "{{ vm_name }}"
    validate_certs: false
  register: snapshots


# - name: List Snapshots Less Than 2 Hours Old
#   anssible.builtin.debug:
#     var: snapshot

# - name: Display Snapshots Less Than 2 Hours Old
#   debug:
#     var: snapshot_facts.snapshots
#   when: snapshot_facts.snapshots is defined and snapshot_facts.snapshots | length > 0