---
- name: Deploy Azure VM from ARM template
  hosts: all
  gather_facts: false
  vars:
    resource_group: "ansible-test-RG"            # Replace with your resource group name
    location: "East US"                          # Replace with your preferred Azure region
    vm_name: "win2016vm"                         # Desired VM name
    vm_size: "Standard_DS1_v2"                   # VM size (adjust based on your requirements)
    admin_username: "ansible"                    # Administrator username for the VM
    admin_password: "ansible"                    # Administrator password for the VM (must meet Azure complexity requirements)
    image:
      offer: "WindowsServer"
      publisher: "MicrosoftWindowsServer"
      sku: "2016-Datacenter"
      version: "latest"
    network_interface: "ansible-NIC"
  tasks:
    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: eastus

    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "ansible-VNet"
        address_prefixes: "10.0.0.0/16"
        location: "{{ location }}"

    - name: Create subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "ansible-Subnet"
        address_prefix: "10.0.1.0/24"
        virtual_network: "ansible-VNet"

    - name: Create network interface
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ network_interface }}"
        location: "{{ location }}"
        subnet_name: "ansible-Subnet"
        virtual_network: "ansible-VNet"
        create_with_security_group: false
        ip_configurations:
          - name: ipconfig1
            primary: true
