---
- name: Play to Delete a VM in Vmware
  hosts: localhost
  gather_facts: false
  tasks:


    - name: Include role to create Linux
      ansible.builtin.include_role:
        name: vmware_remove_linux_machine
