---
- hosts: all
  gather_facts: no
  tasks:
    - name: Remove Old hostname in DNS server
      win_dns_record:
        name: "{{ old_vm }}"
        type: "A"
        zone: "iisl.lab.zone"
        state: absent

    - name: Add New hostname in DNS server
      win_dns_record:
        name: "{{ new_vm }}"
        type: "A"
        zone: "iisl.lab.zone"
        value: "192.168.2.224"
