---
- hosts: all
  gather_facts: no
  tasks:
    - name: Cleanup hostname in host level
      hostname:
        name: "{{ new_vm_name }}.healthix.org"

    - name: Cleanup hostname in VSphere Level
      block:
        - name: Get VM "{{ old_vm_name }}" uuid
          vmware_guest_facts:
            validate_certs: False
            datacenter: "Plainview"
            name: "{{ old_vm_name }}"
          register: vm_facts
        - name: Rename "{{ old_vm_name }}" to "{{ new_vm_name }}" 
          vmware_guest:
            validate_certs: False
            cluster: "RHEL-Automation"
            uuid: "{{ vm_facts.instance.hw_product_uuid }}"
            name: "{{ new_vm_name }}"
      delegate_to: localhost

    - name: Cleanup hostname in Windows DNS Server
      block: Cleanup hostname in Windows DNS Server
      - name: Remove Old hostname in DNS server
        win_dns_record:
          name: "{{ old_vm }}"
          type: "{{item}}"
          zone: "iisl.lab.zone"
          state: absent
        with_items:
          - A
          - PTR
      - name: Add New hostname in DNS server - Creating A Record
        win_dns_record:
          name: "{{ new_vm }}.iisl.lab"
          type: "A"
          zone: "iisl.lab.zone"
          value: "{{new_ip}}"
      - name: Add New hostname in DNS server - Creating PTR Record
        win_dns_record:
          name: "{{ new_ip }}"
          type: "PTR"
          zone: "2.168.192.in-addr.arpa"
          value: "{{new_vm}}.iisl.lab"
    delegate_to: winad.iisl.lab