---
- hosts: all
  gather_facts: no
  tasks:
    - name: Cleanup hostname in DNS server
      win_dns_record:
        name: "{{ old_vm_name }}"
        type: "PTR"
        value: "{{new_vm_name}}"
      delegate_to: 
