---
- hosts: all
  gather_facts: no
  tasks:
    - name: Remove Old hostname in DNS server
      win_dns_record:
        name: "{{ old_vm }}"
        type: "A"
        zone: "iisl.lab.zone"
        state: absent

    - name: Add New hostname in DNS server - Creating A Record
      win_dns_record:
        name: "{{ new_vm }}"
        type: "A"
        zone: "iisl.lab.zone"
        value: "{{new_ip}}"

    - name: Add New hostname in DNS server - Creating PTR Record
      win_dns_record:
        name: "{{ new_ip }}"
        type: "PTR"
        zone: "iisl.lab.zone"
        value: "{{new_vm}}"
