---
- name: Play to ping the host
  hosts: all
  gather_facts: false
  tasks:
      - ansible.builtin.include_role:
          name: linux_ping

      - name: Call the preval.yml playbook from check_service role
        ansible.builtin.include_role:
          name: chceck_service
          tasks_from: preval.yml

      - name: Call the preval.yml playbook from check_service role
        ansible.builtin.include_role:
          name: check_service
          tasks_from: change the file here