---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Create in memory inventory with created VM
    add_host:
      name: "{{ linux_hostname }}"
      ansible_host: "{{ linux_ip_address }}"
      groups: rhel_server
  
- hosts: rhel_server
  gather_facts: no
  tasks:
   - name: Ping the machine
     ping:
   - name: Get the hostname
     debug:
        msg: "Target machine is: {{ inventory_hostname }}" 
    
   - name: Create the user and associated directory
     include_role:
       name: linux_create_user

   - name: Patch the linux machine
     include_role:
       name: linux_patching