---
- name: Play to ping the host
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_role:
         name: linux_ping
- name: Debug Json Variable
  ansible.builtin.debug:
      msg: "{{ vm_info.vms[0].id }}"