---
- name: Leapp Upgrade Playbook
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Call the role to parse Leapp Report
      ansible.builtin.include_role:
        name: leapp_upgrade_7_8
        tasks_from: leapp_parse_report.yml
