---
- name: Leapp Upgrade Playbook
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Call the role for leapp upgrade
      ansible.builtin.include_role: 
        name: leapp_upgrade_7_8
        tasks_from: leapp_fix.yml
