---
- hosts: all
  become_user: yes
  tasks:
    - name: Split the hostname
      set_fact:
        computer_name: "{{ linux_hostname.split('.')[0]}}"

    - name: Print config
      vars:
        msg: |
          Success on:
          - Creating a Virtual Machine named {{ computer_name }}
                        Hostname: {{linux_hostname}}
                        Ip address: {{linux_ip}}
          - Adding the ip address and hostname in forward and reverse DNS search zone, and restarting DNS service in DNS server
          - Creating {{ linux_user }} user in {{ linux_hostname }} with Administrative rights
          - Creating a AD user named {{ linux_user }} in Windows AD server with Administrative rights
          - Updating all the packages except for Kernal on {{ linux_hostname }}
          - Creating the following directories on {{linux_hostname}} machine for {{ linux_user }} user:
                        - /home/{{linux_user}}/ansible
                        - /home/{{linux_user}}/ansible/roles
                        - /home/{{linux_user}}/ansible/collections
      debug:
        msg: "{{ msg.split('\n')}}"
      when: vm_template == "RHEL7"
    
    - name: Print config
      vars:
        msg: |
          Success on:
          - Creating a Virtual Machine named {{ linux_hostname }}
                        Hostname: {{linux_hostname}}
                        Ip address: {{linux_ip}}
          - Adding the ip address and hostname in forward and reverse DNS search zone, and restarting DNS service in DNS server
          - Creating {{ linux_user }} user in {{ linux_hostname }} with Administrative rights
          - Creating a AD user named {{ linux_user }} in Windows AD server with Administrative rights
          - Updating all the packages {{ linux_hostname }}
          - Creating the following directories on {{linux_hostname}} machine for {{ linux_user }} user:
                        - /home/{{linux_user}}/ansible
                        - /home/{{linux_user}}/ansible/roles
                        - /home/{{linux_user}}/ansible/collections
      debug:
        msg: "{{ msg.split('\n')}}"
      when: vm_template == "RHEL8"