---
- name: Initialize disk, mount ISO, and run setup.exe on Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Get disk numbers with raw partitions
      ansible.windows.win_shell: |
        try {
            $disks = Get-Disk | Select-Object Number, Size, PartitionStyle | ConvertTo-Json -Depth 2
            if ($disks -eq $null) { exit 1 }
            $disks
        } catch {
            exit 1
        }
      register: disk_info
      failed_when: disk_info.rc != 0 or disk_info.stdout is not defined or disk_info.stdout | length == 0

    - name: Fail if no disks are found
      ansible.builtin.fail:
        msg: "No disks detected. Please check the system."
      when: disk_info.stdout | from_json | length == 0

    - name: Parse raw partition information
      ansible.builtin.set_fact:
        raw_disks: "{{ disk_info.stdout | from_json | selectattr('PartitionStyle', 'eq', 'RAW') | list }}"

    - name: Fail if no raw disks are found
      ansible.builtin.fail:
        msg: "No raw disks found. Exiting..."
      when: raw_disks | length == 0

    - name: Display raw partition information
      ansible.builtin.debug:
        msg: "{{ raw_disks }}"

    - name: Initialize raw disks (if not already initialized)
      ansible.windows.win_shell: |
        $disk = Get-Disk -Number {{ item.Number }}
        if ($disk.PartitionStyle -eq 'RAW') {
            Initialize-Disk -Number {{ item.Number }} -PartitionStyle GPT
        }
      loop: "{{ raw_disks }}"

    - name: Create a partition and assign a drive letter (if no partition exists)
      ansible.windows.win_shell: |
        $existingPartition = Get-Partition -DiskNumber {{ item.Number }} -ErrorAction SilentlyContinue
        if (-not $existingPartition) {
            $partition = New-Partition -DiskNumber {{ item.Number }} -UseMaximumSize
            Set-Partition -PartitionNumber $partition.PartitionNumber -DiskNumber {{ item.Number }} -NewDriveLetter Z
        }
      loop: "{{ raw_disks }}"

    - name: Format the partition (only if not already formatted)
      ansible.windows.win_shell: |
        $volume = Get-Volume -DriveLetter Z -ErrorAction SilentlyContinue
        if ($volume -and $volume.FileSystem -eq $null) {
            Format-Volume -DriveLetter Z -FileSystem NTFS -NewFileSystemLabel "NewDisk" -Confirm:$false
        }
      when: raw_disks | length > 0
