---
- name: Play to ping the windows host
  hosts: all
  gather_facts: false
  tasks:
      - name: Ping the Windows server for the First time
        ansible.windows.win_ping:

      - name: Ping the Windows server for the Second time
        ansible.windows.win_ping:

      - name: Gather facts of the machine
        ansible.builtin.setup:
        register: machine_facts

      - name: Debug machine_facts
        ansible.builtin.debug:
          var: machine_facts.ansible_facts.ansible_powershell_version
