---
# tasks file for cerate_AD_user
- name: "Create a user"
  community.windows.win_domain_user:
    firstname: "{{ linux_user }}"
    name: "{{ linux_user }}"
    password: "{{ linux_password }}"
    groups: Administrators
    state: present