---
# tasks file for roles/linux_patching
- name: Set the correct hostname
  ansible.builtin.hostname:
    name: "{{ vm_name }}.iisl.lab"
    
- name: Update all the packages except for kernel 
  yum:
    name: '*'
    state: latest
    exclude: kernel*
    skip_broken: yes
  register: upd_result

- name: Print activity
  debug:
    msg: "All the patches except for kernel have been applied to the Tareget hosts"


- name: Set stats for workflow template
  set_stats:
    data:
      linux_ipv4: "{{ linux_ip }}"
      linux_hostname: "{{ vm_name }}.iisl.lab"