---
# tasks file for roles/linux_patching
- name: Set the correct hostname
  ansible.builtin.hostname:
    name: "{{ vm_name }}.iisl.lab"
    
- name: Update all the packages Including the kernel 
  yum:
    name: '*'
    state: latest
    skip_broken: yes
  when: vm_template == "RHEL7"

- name: Update all the packages Including the kernel 
  yum:
    name: '*'
    state: latest
    skip_broken: yes
  when: vm_template == "RHEL8"

- name: Print activity
  debug:
    msg: "All the patches have been applied to the Tareget hosts" #"All the patches except for kernel have been applied to the Tareget hosts"
  when: vm_template == "RHEL7"

- name: Print activity
  debug:
    msg: "All the patches have been applied to the Tareget hosts"
  when: vm_template == "RHEL8"

- name: Set stats for workflow template
  set_stats:
    data:
      linux_ipv4: "{{ linux_ip }}"
      linux_hostname: "{{ vm_name }}.iisl.lab"