---
# tasks file for create_linux_vm
- name: Include vars file
  include_vars:
   - vm_size_details.yml

- name: Select RHEL-8 template
  set_fact:
      linux_template: "rhel8_template"

- name: Parse VM List file
  community.general.read_csv:
    path: vm_detail.csv
    delimiter: ','
    key: hostname
  register: vms

# - name: Call the task to provision multiple machines
