---
# tasks file for register_rhel_subscription
- name: Add Redhat subscription to a specific pool by ID.
  community.general.redhat_subscription:
    state: present
    force_register: yes
    username: '{{ rh_sub_username }}'
    password: '{{ rh_sub_pass }}'
    environment: 'low_impact/RHEL7'
    auto_attach: true
  when: ansible_distribution_major_version == 7

- name: Add Redhat subscription to a specific pool by ID.
  community.general.redhat_subscription:
    state: present
    force_register: yes
    username: '{{ rh_sub_username }}'
    password: '{{ rh_sub_pass }}'
    environment: 'low_impact/RHEL8'
    auto_attach: true
  when: ansible_distribution_major_version == 8