---
- name: Start Leapp OS upgrade
  ansible.builtin.shell: |
    leapp upgrade --target 8.10  
  async: 1000
  poll: 0
  changed_when: true

- name: Pause for 25 minutes and Wait for system to reboot
  ansible.builtin.pause:
    minutes: 25

- name: Check if the log file exists
  ansible.builtin.stat:
    path: /var/log/leapp/leapp-upgrade.log
  register: logfile_stat

- name: Wait for a specific sentence in the log file
  ansible.builtin.wait_for:
    path: '/var/log/leapp/leapp-upgrade.log'
    search_regex: 'Answerfile will be created at /var/log/leapp/answerfile'
    delay: 10
    timeout: 600
  when: logfile_stat.stat.exists

- name: Reboot the machine
  ansible.builtin.reboot:
    reboot_timeout: 1200

- name: Ensure the machine is fully rebooted
  ansible.builtin.shell: |
    cat /etc/redhat-release
  args:
    executable: /bin/bash
  changed_when: false