- name: leapp-upgrade From RHEL7 to RHEL8
  block:
    - name: Start Leapp OS upgrade
      ansible.builtin.shell: >
        set -o pipefail;
        leapp upgrade
        --target 8.10
        --reboot
        2>&1 | tee -a {{ log_file }}
      args:
        executable: /bin/bash
      async: 7200
      poll: 0
      changed_when: true
    - name: Wait for system to reboot
      ansible.builtin.pause:
        minutes: 30
    - name: Wait for the machine to come back online
      ansible.builtin.wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
  rescue:
    - name: leapp-upgrade | Include the parse_leapp_report role to check for inhibitors
      ansible.builtin.include_tasks: leapp_parse_report.yml

- name: Ensure the machine is fully rebooted
  ansible.builtin.shell: >
    until who -b | grep -q $(date +"%Y-%m-%d"); do sleep 10; done
  args:
    executable: /bin/bash
  changed_when: false