---
- name: Default upgrade_inhibited to false
  ansible.builtin.set_fact:
    upgrade_inhibited: false

- name: Collect human readable report results
  ansible.builtin.slurp:
    src: "{{ result_filename }}"
  register: results_txt

- name: Collect JSON report results
  ansible.builtin.slurp:
    src: "{{ result_filename_json }}"
  register: results_json

- name: Parse report results
  ansible.builtin.set_fact:
    leapp_report_txt: "{{ results_txt.content | b64decode | split('\n') }}"
    leapp_report_json: "{{ results_json.content | b64decode | from_json }}"

- name: Check for inhibitors
  ansible.builtin.set_fact:
    upgrade_inhibited: true
  when:
    - (leapp_high_sev_as_inhibitors | default(false, true) | bool and item.severity == 'high (error)') or
      'inhibitor' in item.flags
  loop: "{{ leapp_report_json.entries }}"

- name: Collect inhibitors
  vars:
    high_filter: "{{ '|Risk Factor: high' if leapp_high_sev_as_inhibitors | default(false, true) | bool else '' }}"
  ansible.builtin.command:
    cmd: awk '/\(inhibitor\){{ high_filter }}/,/^-------/' {{ result_filename }}
  register: results_inhibitors
  changed_when: false
  failed_when: false

- name: Display the inhibitors
  ansible.builtin.debug:
    msg: "{{ results_inhibitors.stdout_lines }}"