- name: Start Leapp OS upgrade
  ansible.builtin.shell: |
    leapp upgrade --target 8.10 --reboot 
  args:
    executable: /bin/bash
  async: 1000
  poll: 0
  changed_when: true

- name: Pause for 25 minutes and Wait for system to reboot
  ansible.builtin.pause:
    minutes: 30

- name: Wait for the machine to come back online
  ansible.builtin.wait_for_connection:
    delay: 10 # Number of seconds to wait before starting to poll.
    sleep: 5 # Number of seconds to sleep between checks.
    timeout: 900 #seconds

- name: Ensure the machine is fully rebooted
  ansible.builtin.shell: |
    cat /etc/redhat-release
  args:
    executable: /bin/bash
  changed_when: false