---

  
####################################################################
# - name: Fix preupgrade issues
#   # Here, you can add tasks to handle common preupgrade issues
#   ansible.builtin.debug:
#     msg: "Resolve any issues identified by the preupgrade check manually or with additional tasks."
####################################################################

#################################
####### Run the Upgrade #########
#################################


- name: Run Leapp upgrade to RHEL 8
  ansible.builtin.command: leapp upgrade --target 8.10 -- reboot
  register: upgrade_result
  ignore_errors: true
## Add a fail condition if found anything in Error on update_result

- name: Ping ther server
  ansible.builtin.ping:

# - name: Check Leapp upgrade result
#   ansible.builtin.fail:
#     msg: "Upgrade to RHEL 8 failed. Please check the logs and resolve issues."
#   when: upgrade_result.rc != 0

# - name: Reboot the system after RHEL 8 upgrade
#   ansible.builtin.reboot:
#     reboot_timeout: 3600

# - name: Ensure the system is running RHEL 8
#   ansible.builtin.wait_for_connection:
#     delay: 30
#     sleep: 5
#     timeout: 300
#   when: upgrade_result.rc == 0

# #################################
# ####### Finalize Upgrade ########
# #################################

# - name: Finalize the upgrade to RHEL 8
#   ansible.builtin.command: leapp finalize
#   register: finalize_result
#   ignore_errors: yes

# - name: Check Leapp finalize result
#   ansible.builtin.fail:
#     msg: "Finalize to RHEL 8 failed. Please check the logs and resolve issues."
#   when: finalize_result.rc != 0

# - name: Verify RHEL version
#   ansible.builtin.command: cat /etc/redhat-release
#   register: rhel_version

# - name: Display RHEL version
#   ansible.builtin.debug:
#     msg: "System upgraded to {{ rhel_version.stdout }}"
#   when: rhel_version.stdout is search("Red Hat Enterprise Linux release 8")


- name: Remove remaining RHEL7 packages
  ansible.builting.yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - kernal-workaround
    - "{{ rhel7_package.stdout_lines }}"

...