---
- name: Play to Create a File in Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Create a temporary directory for the script
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Copy the PowerShell script to the remote host
      ansible.windows.win_copy:
        src: file_watcher.ps1
        dest: C:\Temp\file_watcher.ps1

    - name: Run the PowerShell script from the file
      ansible.windows.win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\Temp\file_watcher.ps1
      async: 3600 # Run asynchronously for 1 hour
      poll: 0     # Don't wait for the async task to complete
      register: script_result

    - name: Display async task result
      debug:
        var: script_result
