---
- name: Play to ping the windows host
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping the Windows server for the First time
      ansible.windows.win_ping:

    - name: Debug the payload event data
      ansible.builtin.debug:
        var: ansible_eda.event.payload

    - name: Handle file modification event
      when: ansible_eda.event.payload.event_type == 'modified'
      block:
        - name: Debug the modification event
          ansible.builtin.debug:
            msg: "Event was: {{ ansible_eda.event.payload.event_type }}"
        - name: Debug the name of the file
          ansible.builtin.debug:
            msg: "{{ ansible_eda.event.payload.path | ansible.windows.win_basename  }}"


    - name: Handle file creation event
      when: ansible_eda.event.payload.event_type == 'created'
      block:
        - name: Debug the creation event
          ansible.builtin.debug:
            msg: "Event was: {{ ansible_eda.event.payload.event_type }}"


    - name: Handle file deletion event
      when: ansible_eda.event.payload.event_type == 'deleted'
      block:
        - name: Debug the deletion event
          ansible.builtin.debug:
            msg: "Event was: {{ ansible_eda.event.payload.event_type }}"
