---
- name: Play to Create a File in Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Generate a random string 🎲
      ansible.builtin.set_fact:
        random_string: "{{ ''.join(lookup('password', '/dev/null chars=ascii_letters,digits length=12')) }}"

    - name: Display the generated string (optional)
      ansible.builtin.debug:
        var: random_string

    - name: Create a file with content on Windows
      ansible.windows.win_copy:
        dest: C:\\Users\\Administrator\\Downloads\\ansible-test.txt
        content: |
          This is the first line of content.
          This is the second line.

    - name: Append the random string to a file
      community.windows.win_lineinfile:
        path: C:\\Users\\Administrator\\Downloads\\ansible-test.txt
        line: "{{ random_string }}"
        create: true
        state: present 