---
- name: Play to Create a File in Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Create a file with content on Windows
      ansible.windows.win_file:
        dest: C:\\Users\\Administrator\\Downloads\\ansible-test.txt
        state: touch

    - name: Create a file with content on Windows
      ansible.windows.win_copy:
        dest: C:\\Users\\Administrator\\Downloads\\ansible-test.txt
        content: |
          This is the first line of content.
            This is the second line. 