---
- name: Play to ping the windows host
  hosts: all
  gather_facts: false
  vars:
    backup_directory: 'C:\temp'
  tasks:
    - name: Ping the Windows server for the First time
      ansible.windows.win_ping:

    - name: Debug the payload event data
      ansible.builtin.debug:
        var: ansible_eda.event.payload

################################################################
################### Event for File Modification ################
################################################################

    - name: Handle file modification event
      when: ansible_eda.event.payload.event_type == 'modified'
      block:
        - name: Debug the modification event
          ansible.builtin.debug:
            msg: "Event: {{ ansible_eda.event.payload.event_type }}"

        - name: Debug the name of the file Modified
          vars:
            msg: |
              - Name of the File Modified: {{ ansible_eda.event.payload.path | ansible.builtin.win_basename }}
              - Modified File Path: {{ ansible_eda.event.payload.path }}"
          ansible.builtin.debug:
            msg: "{{ msg.split('\n')}}"

        # - name: Create backup of the file with datestamp
        #   vars:
        #     timestamp: "{{ ansible_eda.event.payload.timestamp | regex_replace('[^a-zA-Z0-9]', '') }}"
        #   ansible.windows.win_copy:
        #     src: "{{ ansible_eda.event.payload.path }}"
        #     dest: "{{ backup_directory }}/{{ ansible_eda.event.payload.path | ansible.builtin.win_basename }}_{{ timestamp }}_backup.txt"
        #     remote_src: true

################################################################
################### Event for File Creation ####################
################################################################

    - name: Handle file creation event
      when: ansible_eda.event.payload.event_type == 'created'
      block:
        - name: Debug the creation event
          ansible.builtin.debug:
            msg: "Event: {{ ansible_eda.event.payload.event_type }}"

        - name: Debug the name of the file Created
          vars:
            msg: |
              - Name of the File Created: {{ ansible_eda.event.payload.path | ansible.builtin.win_basename }}
              - Created File Path: {{ ansible_eda.event.payload.path }}"
          ansible.builtin.debug:
            msg: "{{ msg.split('\n')}}"

        # - name: Create backup of the file with datestamp
        #   vars:
        #     timestamp: "{{ ansible_eda.event.payload.timestamp | regex_replace('[^a-zA-Z0-9]', '') }}"
        #   ansible.windows.win_copy:
        #     src: "{{ ansible_eda.event.payload.path }}"
        #     dest: "{{ backup_directory }}\\{{ ansible_eda.event.payload.path | ansible.builtin.win_basename }}_{{ timestamp }}_backup.txt"
        #     remote_src: true

################################################################
################### Event for File Deletion ####################
################################################################

    - name: Handle file deletion event
      when: ansible_eda.event.payload.event_type == 'deleted'
      block:
        - name: Debug the name of the file Deleted
          vars:
            msg: |
              - Name of the File Deleted: {{ ansible_eda.event.payload.path | ansible.builtin.win_basename }}
              - Deleted File Path: {{ ansible_eda.event.payload.path }}"
          ansible.builtin.debug:
            msg: "{{ msg.split('\n')}}"

        - name: Debug the deletion event
          ansible.builtin.debug:
            msg: "Event: {{ ansible_eda.event.payload.event_type }}"

################################################################
############### Save event payload to a file ###################
################################################################
    - name: Append log block to report file on Windows
      ansible.windows.win_shell: |
        $log_entry ="`n" +
                    "      - ""Event Type:{{ ansible_eda.event.payload.event_type }}""`n" +
                    "      - ""Path: {{ ansible_eda.event.payload.path }}""`n" +
                    "      - ""User: {{ ansible_eda.event.payload.user }}""`n" +
                    "      - ""Timestamp: {{ ansible_eda.event.payload.timestamp }}""`n" +
                    "      - ""Diff: {{ ansible_eda.event.payload.diff }}""`n" +
                    "`n"
        Add-Content -Path report_logs.txt -Value $log_entry
      args:
        chdir: C:\Users\Administrator\pfizer\win-audit

    # - name: Append event payload as a block
    #   community.windows.win_lineinfile:
    #     path: C:\Users\Administrator\pfizer\win-audit\report_logs.txt
    #     line: "{{ item }}"
    #     state: present
    #     create: true
    #     insertafter: EOF
    #   loop:
    #     - "Event Type:   {{ ansible_eda.event.payload.event_type }}"
    #     - "Path:         {{ ansible_eda.event.payload.path }}"
    #     - "User:         {{ ansible_eda.event.payload.user }}"
    #     - "Timestamp:    {{ ansible_eda.event.payload.timestamp }}"
    #     - "Diff:         {{ ansible_eda.event.payload.diff }}"