---
- name: Play to Create a File in Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Debug the payload event data
      ansible.builtin.debug:
        msg: "{{ ansible_eda.event.payload }}"

    - name: Ensure the backup directory exists
      ansible.windows.win_file:
        path: "{{ backup_directory }}"
        state: directory

    - name: Generate the CSV file from the Jinja2 template
      ansible.windows.win_template:
        src: templates/report.csv.j2
        dest: 'C:\Users\Administrator\pfizer\winaudit\event_report_{{ ansible_eda.event.payload.timestamp | regex_replace("[^a-zA-Z0-9]", "") }}.csv