- name: Install epel repo package
  shell: |
    curl -O https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  args:
    chdir: /tmp

- name: install epel repo
  yum:
    name: /tmp/epel-release-latest-7.noarch.rpm
    use_backend: yum3

