- name: Install epel repo
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel-release-latest-7.noarch.rpm

- name: Install epel repo
  shell:
   cmd: yum -y install epel-release-latest-7.noarch.rpm
   chdir: /tmp/