- name: Install epel repo
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel/epel-release-latest-7.noarch.rpm

- name: Install epel repo
  shell: | 
   yum -y install /tmp/epel-release-latest-7.noarch.rpm