#- name: Download python
#  shell: |
#   rpm -i https://download.fedora.redhat.com/pub/fedora/linux/development/i386/os/Packages/python-2.5.1-18.fc9.i386.rpm
#  args:
#    chdir: /tmp
#
#- name: Download yum repo package
#  shell:
#   curl -O http://mirror.centos.org/centos/7/os/x86_64/Packages/yum-3.4.3-168.el7.centos.noarch.rpm
#  args:
#   chdir: /tmp
#
#- name: Install yum repo
#  shell: |
#   rpm -Uhv yum-3.4.3-168.el7.centos.noarch.rpm
#  args:
#    chdir: /tmp

#- name: Install epel repo package
#  shell: |
#   curl -O https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#  args:
#   chdir: /tmp

- name: install epel repo
  yum:
    name: epel-release
    use_backend: yum
# - name: Install epel repo
# yum:
#   name: /tmp/epel-release-latest-7.noarch.rpm
#   state: present
