---
# tasks file for install_mariadb
- name: Install epel repo
  include_tasks: install_epel.yml
  
- name: Install mariadb packages
  yum:
    name:
      - python3-PyMySQL
      - mariadb-server
    state: latest

- name: Start mariadb service
  service:
    name: mariadb
    enabled: true
    state: started

- name: mysql_root_password
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    host: localhost

- name: remove remote root
  community.mysql.mysql_user:
    check_implicit_admin: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    host: "{{ ansible_fqdn }}"
    state: absent

- name: Restart mariadb service
  ansible.builtin.service:
      name: mariadb
      state: reloaded