---
#################################
####### Prep the machine ########
#################################

# - name: Unset RHEL version
#   ansible.builtin.shell: subscription-manager release --unset

# - name: Ensure system is updated -- Makes system to 7.9
#   ansible.builtin.yum:
#     name: '*'
#     state: latest

# - name: Install Leapp packages
#   ansible.builtin.yum:
#     name: "{{ item }}"
#     state: present
#     enablerepo: "rhel-7-server-rpms,rhel-7-server-extras-rpms"
#   loop:
#       - leapp
#       - leapp-repository 

- name: Run Leapp preupgrade to RHEL 8
  ansible.builtin.command: leapp preupgrade --target 8.10
  register: preupgrade_result
  ignore_errors: yes

- name: Debug the preupgrade_result
  ansible.builtin.debug:
    var: preupgrade_result.stdout_lines[0]
# - debug:
#     var: present_preupgrade_out

- name: Search for Inhibitors
  ansible.builtin.set_fact:
    inhibitors_count: "{{preupgrade_result.stdout_lines[0] | regex_search('Inhibitors:\\s+(\\d+)', '\\1')}}"

- name: Ensure inhibitors count is set
  ansible.builtin.set_fact:
    inhibitors_count: "{{ inhibitors_count_str | default('0') | int }}"

- debug:
    msg: "NO Inhibitors present"
  when: inhibitors_count == 0 

- name: Fail if Inhibitors not 0
  ansible.builtin.fail:
    msg: "Inhibitors:         {{ inhibitors_count }}"
  when: inhibitors_count != 0

  
####################################################################
# - name: Fix preupgrade issues
#   # Here, you can add tasks to handle common preupgrade issues
#   ansible.builtin.debug:
#     msg: "Resolve any issues identified by the preupgrade check manually or with additional tasks."
####################################################################

#################################
####### Run the Upgrade #########
#################################


# - name: Run Leapp upgrade to RHEL 8
#   ansible.builtin.command: leapp upgrade
#   register: upgrade_result
#   ignore_errors: yes

# - name: Check Leapp upgrade result
#   ansible.builtin.fail:
#     msg: "Upgrade to RHEL 8 failed. Please check the logs and resolve issues."
#   when: upgrade_result.rc != 0

# - name: Reboot the system after RHEL 8 upgrade
#   ansible.builtin.reboot:
#     reboot_timeout: 3600

# - name: Ensure the system is running RHEL 8
#   ansible.builtin.wait_for_connection:
#     delay: 30
#     sleep: 5
#     timeout: 300
#   when: upgrade_result.rc == 0

# #################################
# ####### Finalize Upgrade ########
# #################################

# - name: Finalize the upgrade to RHEL 8
#   ansible.builtin.command: leapp finalize
#   register: finalize_result
#   ignore_errors: yes

# - name: Check Leapp finalize result
#   ansible.builtin.fail:
#     msg: "Finalize to RHEL 8 failed. Please check the logs and resolve issues."
#   when: finalize_result.rc != 0

# - name: Verify RHEL version
#   ansible.builtin.command: cat /etc/redhat-release
#   register: rhel_version

# - name: Display RHEL version
#   ansible.builtin.debug:
#     msg: "System upgraded to {{ rhel_version.stdout }}"
#   when: rhel_version.stdout is search("Red Hat Enterprise Linux release 8")