---
# tasks file for configure_dns
- name: Get the last octate of the ip address
  ansible.builtin.set_fact:
   ip_last_octate:  "{{linux_ip_address.split('.')[3] }}"

- name: Get the hostname
  ansible.builtin.set_fact:
   short_hostname: "{{linux_hostname.split('.')[0] }}"

- name: Check server name
  ansible.builtin.shell: |
     hostname -I
  register: server_hostname

- name: Debug hostname
  ansible.builtin.debug:
    var: server_hostname

- name: Add server entry in forward DNS zone
  ansible.builtin.lineinfile:
    dest: /var/named/iisl.lab.zone
    line: "{{ short_hostname }}   IN   A  {{ linux_ip_address }}"

- name: Add server entry in reverse DNS zone
  ansible.builtin.lineinfile:
    dest: /var/named/reverse.2.168.192.zone
    line: "{{ ip_last_octate }}  IN  PTR  {{ linux_hostname }}. "

- name: Restart DNS serveice
  ansible.builtin.service:
   name: named
   state: restarted

- name: Display success message
  ansible.builtin.debug:
    msg: " The created VM has been added to the DNS server "


- name: Set stats for workflow template
  ansible.builtin.set_stats:
    data:
      linux_ip: "{{ linux_ip_address }}"
      linux_hostname: "{{ vm_name }}.iisl.lab"