---
# tasks file for create_multiple_linux_vm
####################################################################
####################### Provision the server #######################
####################################################################

- name: Parse VM List file
  community.general.read_csv:
    path: vm_detail.csv
    delimiter: ','
    key: server_name
  register: vms

- name: debug the csv file
  debug:
    var: vms

- name: Provision RHEL server
  include: provisioning_play.yml
  loop: "{{ vms.dict|dict2items }}" 
