---
# tasks file for create_multiple_linux_vm
####################################################################
####################### Provision the server #######################
####################################################################

- name: Parse VM List file
  community.general.read_csv:
    path: vm_detail.csv
    delimiter: ','
    key: hostname
  register: vm_details

- name: debug the csv file
  debug:
    var: vm_details

# - name: Provision RHEL server
#   include: provisioning_play.yml